import type { Metadata } from 'next'
import { ThemeProvider } from '@/context/ThemeContext'
import { ToastContextProvider } from '@/context/ToastProvider'
import '@/styles/global.css'

// metadata
export const metadata: Metadata = {
  title: 'Xenia Dev',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="fr">
      <body suppressHydrationWarning={true}>
        <ThemeProvider>
          <ToastContextProvider>
            <div className="flex flex-col bg-[var(--surface-background)]">
              <main>{children}</main>
            </div>
          </ToastContextProvider>
        </ThemeProvider>
      </body>
    </html>
  )
}
