import type { Metadata } from 'next'
import { ThemeProvider } from '@/context/ThemeContext'
import '@/styles/global.css'

// metadata
export const metadata: Metadata = {
  title: 'Portfolio',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="fr">
      <body suppressHydrationWarning={true}>
        <ThemeProvider>
          <div className="flex flex-col bg-[var(--surface-background)]">
            <main>{children}</main>
          </div>
        </ThemeProvider>
      </body>
    </html>
  )
}
