import type { Metadata } from 'next';
import '@/styles/reset.css';
import "@/styles/global.css";

// metadata
export const metadata: Metadata = {
  title: 'Portfolio',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="fr">
      <body suppressHydrationWarning={true}>
        <div className="flex w-full bg-[var(--surface-background)]">
          <main className="h-screen w-full overflow-auto">{children}</main>
        </div>
      </body>
    </html>
  )
}
